import 'package:chat_dating_app/models/CheckboxObject.dart';

var hobbyList = [
  CheckboxObject(title: 'Thể thao'),
  CheckboxObject(title: 'Nấu ăn'),
  CheckboxObject(title: 'Đọc sách'),
  CheckboxObject(title: 'Nghe nhạc'),
  CheckboxObject(title: 'Đi chơi'),
  CheckboxObject(title: 'Xem phim'),
  CheckboxObject(title: 'Vẽ tranh'),
  CheckboxObject(title: 'Chụp ảnh'),
  CheckboxObject(title: 'Chơi game'),
  CheckboxObject(title: 'Cắm trại'),
  CheckboxObject(title: 'Mua sắm'),
  CheckboxObject(title: 'Làm đồ thủ công'),
  CheckboxObject(title: 'Làm từ thiện'),
  CheckboxObject(title: 'Làm bánh'),
  CheckboxObject(title: 'Nuôi động vật'),
  CheckboxObject(title: 'Trồng cây'),
  CheckboxObject(title: 'Thể thao'),
  CheckboxObject(title: 'Nấu ăn'),
  CheckboxObject(title: 'Đọc sách'),
  CheckboxObject(title: 'Nghe nhạc'),
  CheckboxObject(title: 'Đi chơi'),
  CheckboxObject(title: 'Xem phim'),
  CheckboxObject(title: 'Vẽ tranh'),
  CheckboxObject(title: 'Chụp ảnh'),
  CheckboxObject(title: 'Chơi game'),
  CheckboxObject(title: 'Cắm trại'),
  CheckboxObject(title: 'Mua sắm'),
  CheckboxObject(title: 'Làm đồ thủ công'),
  CheckboxObject(title: 'Làm từ thiện'),
  CheckboxObject(title: 'Làm bánh'),
  CheckboxObject(title: 'Nuôi động vật'),
  CheckboxObject(title: 'Trồng cây'),
];

var personalityList = [
  CheckboxObject(title: 'Hài hước'),
  CheckboxObject(title: 'Tự tin'),
  CheckboxObject(title: 'Nhạy cảm'),
  CheckboxObject(title: 'Năng động'),
  CheckboxObject(title: 'Trầm lặng'),
  CheckboxObject(title: 'Thân thiện'),
  CheckboxObject(title: 'Sáng tạo'),
  CheckboxObject(title: 'Tỉ mỉ'),
  CheckboxObject(title: 'Lạc quan'),
  CheckboxObject(title: 'Bình tĩnh'),
  CheckboxObject(title: 'Quyết đoán'),
  CheckboxObject(title: 'Chân thành'),
  CheckboxObject(title: 'Cởi mở'),
  CheckboxObject(title: 'Dễ gần'),
  CheckboxObject(title: 'Kiên nhẫn'),
  CheckboxObject(title: 'Tinh tế'),
  CheckboxObject(title: 'Tốt bụng'),
  CheckboxObject(title: 'Kỷ luật'),
  CheckboxObject(title: 'Khéo léo'),
  CheckboxObject(title: 'Nhiệt tình'),
];
